# fly.toml app configuration file generated for bitr-backend on 2025-09-05T12:03:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bitr-backend'
primary_region = 'fra'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[processes]
  app = 'npm run start:coordinated'
  indexer = 'npm run indexer'
  workers = 'npm run workers:coordinated'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 768
  processes = ['indexer']

[[vm]]
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
  processes = ['workers']
