# fly.toml app configuration file generated for bitr-backend on 2025-09-05T12:03:40+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bitr-backend'
primary_region = 'fra'

[build]
  dockerfile = 'backend/Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[processes]
  app = 'npm run start'
  indexer = 'npm run indexer'
  workers = 'npm run workers:coordinated'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

# Health checks for the main API
[[http_service.http_checks]]
  grace_period = "30s"
  interval = "15s"
  method = "get"
  path = "/health"
  protocol = "http"
  restart_limit = 3
  timeout = "5s"

# Main API server VM - ONLY API, no background services
[[vm]]
  processes = ['app']
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 2048  # Increased memory for better stability
  region = 'fra'
  # Prevent auto-stopping for API server
  auto_stop_machines = false
  min_machines_running = 1

# Indexer VM (blockchain event indexers)
[[vm]]
  processes = ['indexer']
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 768
  region = 'fra'
  # Disable auto-stopping for indexers to prevent frequent restarts
  auto_stop_machines = false
  min_machines_running = 1

# Workers VM (consolidated background workers with all cron jobs)
[[vm]]
  processes = ['workers']
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
  region = 'fra'
  # Disable auto-stopping for workers to prevent frequent restarts
  auto_stop_machines = false
  min_machines_running = 1
